repos:
  - repo: https://github.com/psf/black
    rev: 21.7b0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.3.1
    hooks:
      - id: check-github-workflows
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
