# Generic name since the names of the source code is needs some refactoring first
from gitbot.lib import extract_author

event = {
    "ref": "refs/heads/master",
    "before": "0a7860586e6103bcb9ed442248773f478e3327f3",
    "after": "05a1b0078e673fa21d8b21192761719be358b7fc",
    "repository": {
        "id": 873328,
        "node_id": "MDEwOlJlcG9zaXRvcnk4NzMzMjg=",
        "name": "sentry",
        "full_name": "getsentry/sentry",
        "private": False,
        "owner": {
            "name": "getsentry",
            "email": None,
            "login": "getsentry",
            "id": 1396951,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTY5NTE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1396951?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/getsentry",
            "html_url": "https://github.com/getsentry",
            "followers_url": "https://api.github.com/users/getsentry/followers",
            "following_url": "https://api.github.com/users/getsentry/following{/other_user}",
            "gists_url": "https://api.github.com/users/getsentry/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/getsentry/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/getsentry/subscriptions",
            "organizations_url": "https://api.github.com/users/getsentry/orgs",
            "repos_url": "https://api.github.com/users/getsentry/repos",
            "events_url": "https://api.github.com/users/getsentry/events{/privacy}",
            "received_events_url": "https://api.github.com/users/getsentry/received_events",
            "type": "Organization",
            "site_admin": False,
        },
        "html_url": "https://github.com/getsentry/sentry",
        "description": "Sentry is cross-platform application monitoring, with a focus on error reporting.",
        "fork": False,
        "url": "https://github.com/getsentry/sentry",
        "forks_url": "https://api.github.com/repos/getsentry/sentry/forks",
        "keys_url": "https://api.github.com/repos/getsentry/sentry/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/getsentry/sentry/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/getsentry/sentry/teams",
        "hooks_url": "https://api.github.com/repos/getsentry/sentry/hooks",
        "issue_events_url": "https://api.github.com/repos/getsentry/sentry/issues/events{/number}",
        "events_url": "https://api.github.com/repos/getsentry/sentry/events",
        "assignees_url": "https://api.github.com/repos/getsentry/sentry/assignees{/user}",
        "branches_url": "https://api.github.com/repos/getsentry/sentry/branches{/branch}",
        "tags_url": "https://api.github.com/repos/getsentry/sentry/tags",
        "blobs_url": "https://api.github.com/repos/getsentry/sentry/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/getsentry/sentry/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/getsentry/sentry/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/getsentry/sentry/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/getsentry/sentry/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/getsentry/sentry/languages",
        "stargazers_url": "https://api.github.com/repos/getsentry/sentry/stargazers",
        "contributors_url": "https://api.github.com/repos/getsentry/sentry/contributors",
        "subscribers_url": "https://api.github.com/repos/getsentry/sentry/subscribers",
        "subscription_url": "https://api.github.com/repos/getsentry/sentry/subscription",
        "commits_url": "https://api.github.com/repos/getsentry/sentry/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/getsentry/sentry/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/getsentry/sentry/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/getsentry/sentry/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/getsentry/sentry/contents/{+path}",
        "compare_url": "https://api.github.com/repos/getsentry/sentry/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/getsentry/sentry/merges",
        "archive_url": "https://api.github.com/repos/getsentry/sentry/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/getsentry/sentry/downloads",
        "issues_url": "https://api.github.com/repos/getsentry/sentry/issues{/number}",
        "pulls_url": "https://api.github.com/repos/getsentry/sentry/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/getsentry/sentry/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/getsentry/sentry/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/getsentry/sentry/labels{/name}",
        "releases_url": "https://api.github.com/repos/getsentry/sentry/releases{/id}",
        "deployments_url": "https://api.github.com/repos/getsentry/sentry/deployments",
        "created_at": 1283206001,
        "updated_at": "2021-07-27T00:01:26Z",
        "pushed_at": 1627345078,
        "git_url": "git://github.com/getsentry/sentry.git",
        "ssh_url": "git@github.com:getsentry/sentry.git",
        "clone_url": "https://github.com/getsentry/sentry.git",
        "svn_url": "https://github.com/getsentry/sentry",
        "homepage": "https://sentry.io",
        "size": 208411,
        "stargazers_count": 28598,
        "watchers_count": 28598,
        "language": "Python",
        "has_issues": True,
        "has_projects": False,
        "has_downloads": True,
        "has_wiki": False,
        "has_pages": False,
        "forks_count": 3178,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 378,
        "license": {
            "key": "other",
            "name": "Other",
            "spdx_id": "NOASSERTION",
            "url": None,
            "node_id": "MDc6TGljZW5zZTA=",
        },
        "forks": 3178,
        "open_issues": 378,
        "watchers": 28598,
        "default_branch": "master",
        "stargazers": 28598,
        "master_branch": "master",
        "organization": "getsentry",
    },
    "pusher": {
        "name": "AniketDas-Tekky",
        "email": "85517732+AniketDas-Tekky@users.noreply.github.com",
    },
    "organization": {
        "login": "getsentry",
        "id": 1396951,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTY5NTE=",
        "url": "https://api.github.com/orgs/getsentry",
        "repos_url": "https://api.github.com/orgs/getsentry/repos",
        "events_url": "https://api.github.com/orgs/getsentry/events",
        "hooks_url": "https://api.github.com/orgs/getsentry/hooks",
        "issues_url": "https://api.github.com/orgs/getsentry/issues",
        "members_url": "https://api.github.com/orgs/getsentry/members{/member}",
        "public_members_url": "https://api.github.com/orgs/getsentry/public_members{/member}",
        "avatar_url": "https://avatars.githubusercontent.com/u/1396951?v=4",
        "description": "Real-time crash reporting for your web apps, mobile apps, and games.",
    },
    "sender": {
        "login": "AniketDas-Tekky",
        "id": 85517732,
        "node_id": "MDQ6VXNlcjg1NTE3NzMy",
        "avatar_url": "https://avatars.githubusercontent.com/u/85517732?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/AniketDas-Tekky",
        "html_url": "https://github.com/AniketDas-Tekky",
        "followers_url": "https://api.github.com/users/AniketDas-Tekky/followers",
        "following_url": "https://api.github.com/users/AniketDas-Tekky/following{/other_user}",
        "gists_url": "https://api.github.com/users/AniketDas-Tekky/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/AniketDas-Tekky/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/AniketDas-Tekky/subscriptions",
        "organizations_url": "https://api.github.com/users/AniketDas-Tekky/orgs",
        "repos_url": "https://api.github.com/users/AniketDas-Tekky/repos",
        "events_url": "https://api.github.com/users/AniketDas-Tekky/events{/privacy}",
        "received_events_url": "https://api.github.com/users/AniketDas-Tekky/received_events",
        "type": "User",
        "site_admin": False,
    },
    "created": False,
    "deleted": False,
    "forced": False,
    "base_ref": None,
    "compare": "https://github.com/getsentry/sentry/compare/0a7860586e61...05a1b0078e67",
    "commits": [
        {
            "id": "05a1b0078e673fa21d8b21192761719be358b7fc",
            "tree_id": "8fbe55602562d82a6f0fc809da87d09ef7847ec8",
            "distinct": True,
            "message": "feat(codeowners): Update codeowners schema on code mapping update (#27770)\n\nWhen code mappings are updated by the user, this can change the codeowners file. We need to trigger an update to the code owners schema in this case.\r\n\r\nFixes API-2002",
            "timestamp": "2021-07-26T17:17:57-07:00",
            "url": "https://github.com/getsentry/sentry/commit/05a1b0078e673fa21d8b21192761719be358b7fc",
            "author": {
                "name": 'Aniket Das "Tekky',
                "email": "85517732+AniketDas-Tekky@users.noreply.github.com",
                "username": "AniketDas-Tekky",
            },
            "committer": {
                "name": "GitHub",
                "email": "noreply@github.com",
                "username": "web-flow",
            },
            "added": [],
            "removed": [],
            "modified": ["src/sentry/models/integration.py"],
        }
    ],
    "head_commit": {
        "id": "05a1b0078e673fa21d8b21192761719be358b7fc",
        "tree_id": "8fbe55602562d82a6f0fc809da87d09ef7847ec8",
        "distinct": True,
        "message": "feat(codeowners): Update codeowners schema on code mapping update (#27770)\n\nWhen code mappings are updated by the user, this can change the codeowners file. We need to trigger an update to the code owners schema in this case.\r\n\r\nFixes API-2002",
        "timestamp": "2021-07-26T17:17:57-07:00",
        "url": "https://github.com/getsentry/sentry/commit/05a1b0078e673fa21d8b21192761719be358b7fc",
        "author": {
            "name": 'Aniket Das "Tekky',
            "email": "85517732+AniketDas-Tekky@users.noreply.github.com",
            "username": "AniketDas-Tekky",
        },
        "committer": {
            "name": "GitHub",
            "email": "noreply@github.com",
            "username": "web-flow",
        },
        "added": [],
        "removed": [],
        "modified": ["src/sentry/models/integration.py"],
    },
}


def test_extract_author():
    author = extract_author(event)
    assert (
        author == "Aniket Das Tekky <85517732+AniketDas-Tekky@users.noreply.github.com>"
    )
