name: CI

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2
      - name: Builds docker image
        run: docker build --tag sentry-deploy-sync-hook:latest .

  # build-deploy:
  #   name: build and deploy
  #   if: github.ref == 'refs/heads/production'
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     # Setup gcloud CLI
  #     - name: Setup gcloud CLI
  #       uses: google-github-actions/setup-gcloud@master
  #       with:
  #         # TODO: Find this info and check with Billy
  #         service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
  #         service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

  #     # XXX: Functions or Run?
  #     # Deploy to Google Cloud Functions
  #     - name: Deploy
  #       id: deploy
  #       env:
  #         GH_WEBHOOK_SECRET: ${{ secrets.GH_WEBHOOK_SECRET }}
  #       run: |
  #         echo "::set-output name=deploy-start::$(date +%s)"
  #         bin/deploy.sh

  #     - name: Sentry Release
  #       uses: getsentry/action-release@v1.0.0
  #       with:
  #         environment: 'production'  # XXX: Determine this
  #         started_at: ${{ steps.deploy.outputs.deploy-start }}
  #         version: ${{ env.VERSION }}  # XXX: Determine this