name: CI

on:
  pull_request:

jobs:
  docker:
    name: docker & dev env works
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          # We are not yet using the new naming in the deploy workflow
          docker build -t gitbot:latest .
          docker run -p 8080:8080 -d -e GOOGLE_APPLICATION_CREDENTIALS -e FAST_STARTUP=1 gitbot:latest
          sleep 10 && curl --request POST http://0.0.0.0:8080

      - name: Test local dev starts up
        run: |
          docker-compose up -d
          docker-compose down
  
  tests:
    name: unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          pip install -U pip wheel
          pip install -r requirements.txt -r requirements-dev.txt
      
      - name: Run tests
        run: |
          pip install -U pip wheel
          pip install -r requirements.txt -r requirements-dev.txt
          pytest tests/test.py
