name: CI

on:
  push:
    branches:
      - master
      - production
  pull_request:

jobs:
  docker:
    name: docker builds
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      # Run only on PR because it will on `build-deploy` on master & production
      if: "startsWith(github.ref, 'refs/pull')"
      run: |
        docker build .

    # XXX: Add check that verifies that a valid SSH key was used
    - name: Test local dev starts up
      run: |
        docker-compose up -d
        docker-compose down

  build-deploy:
    if: github.ref == 'refs/heads/master'
    name: build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # Only staging uploads an image to the registry
      - name: Upload
        run: |
          ./bin/upload.sh
          echo "::set-output name=deploy-start::$(date +%s)"
          ./bin/deploy.sh staging

      - name: Sentry Release
        uses: getsentry/action-release@v1.0.0
        env:
          SENTRY_ORG: sentry
          SENTRY_PROJECT: sentry-deploy-sync-hook
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        with:
          environment: staging
          started_at: ${{ steps.deploy.outputs.deploy-start }}
