name: CI

on:
  pull_request:

jobs:
  docker:
    name: docker & dev env works
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          # We are not yet using the new naming in the deploy workflow
          docker build -t gitbot:latest .
          docker run -d -e GOOGLE_APPLICATION_CREDENTIALS gitbot:latest

      - name: Test local dev starts up
        run: |
          docker-compose up -d
          docker-compose down
