name: CI

on:
  pull_request:

jobs:
  docker:
    name: docker & dev env works
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          # We are not yet using the new naming in the deploy workflow
          docker build -t gitbot:latest .

      - name: Run image & ingest
        run: |
          container_id=$(docker run -p 8080:8080 -d -e GOOGLE_APPLICATION_CREDENTIALS -e FAST_STARTUP=1 gitbot:latest)
          sleep 10 && curl --request POST http://0.0.0.0:8080 || docker logs $container_id && exit 1

  flask:
    name: test flask starts
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          pip install -U pip wheel
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - name: Test that flask starts
        run: |-
          # This saves the initial checkout of the repos and let's the Flask app initialize quickly
          export FAST_STARTUP=1
          nohup flask run &
          sleep 3 && python ingest.py

  tests:
    name: unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          pip install -U pip wheel
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - name: Run tests
        run: |
          pytest
