name: CI

on:
  # push:
  #   branches:
  #     - master
  #     - production
  pull_request:

jobs:
  build-deploy:
    name: build and deploy
    # For now let it run on PRs
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Builds docker image
        run: |
          docker build --tag sentry-deploy-sync-hook:latest .
          # Test that the dev env starts up
          docker-compose up -d
          docker-compose down

      # Setup gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # Deploy to Google Cloud Run (only staging)
      - name: Deploy
        # XXX: Add this restriction back when we merge to master
        # if: github.ref == 'refs/heads/master'
        id: deploy
        run: |
          echo "::set-output name=deploy-start::$(date +%s)"
          bin/deploy.sh

  #     - name: Sentry Release
  #       uses: getsentry/action-release@v1.0.0
  #       with:
  #         environment: 'production'  # XXX: Determine this
  #         started_at: ${{ steps.deploy.outputs.deploy-start }}
  #         version: ${{ env.VERSION }}  # XXX: Determine this