name: Deploy

# TODO: Add support for triggering workflow manually for a production deployment OR a staging deployment
on:
  push:
    branches:
      - master
  # XXX: Disable before merging
  pull_request:

jobs:
  build-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      SENTRY_ORG: sentry
      SENTRY_PROJECT: sentry-deploy-sync-hook
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.5.0
        with:
          service: sentry-deploy-sync-hook-staging 
          image: gcr.io/sentry-dev-tooling/sentry-deploy-sync-hook
          credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Use Output
        run: curl "${{ steps.deploy.outputs.url }}"

      - name: Sentry Release
        uses: getsentry/action-release@v1.0.0
        with:
          environment: staging
          started_at: ${{ steps.deploy.outputs.deploy-start }}
