name: Deploy
env:
  PROJECT_ID: sentry-dev-tooling
  # XXX: On the next pass, add support for triggering the workflow manually for a production deployment
  # OR a staging deployment. Switch back to automatically deploying staging
  # Currently only supporting production
  SERVICE: sentry-deploy-sync-hook-staging
  # XXX: This needs to be determined based on the service
  ENVIRONMENT: staging
  REGION: us-central1

on:
  push:
    branches:
      - master
  # XXX: Temp change
  pull_request:
  workflow_dispatch:
    inputs:
      service:
        description: 'GCR service to deploy to.'
        required: true
        default: 'sentry-deploy-sync-hook-staging'

jobs:
  build-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true  # Set to true to authenticate the Cloud Run action

      # This gives the ability to push to the Google Registry
      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t us.gcr.io/$PROJECT_ID/sentry-deploy-sync-hook:$GITHUB_SHA .
          docker push us.gcr.io/$PROJECT_ID/sentry-deploy-sync-hook:$GITHUB_SHA

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.5.0
        with:
          service: ${{ env.SERVICE }}
          image: us.gcr.io/${{ env.PROJECT_ID }}/sentry-deploy-sync-hook:${{ github.sha }}
          region: ${{ env.REGION }}
      
      - name: Env variables
        run: |-
          env
          echo "- in ${{ github.event.inputs.service }}!"

      # - name: Sentry Release
      #   uses: getsentry/action-release@v1.1.5
      #   with:
      #     environment: ${{ env.ENVIRONMENT }}
      #   env:
      #     SENTRY_ORG: sentry
      #     SENTRY_PROJECT: sentry-deploy-sync-hook
      #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
